### ISSUE TITLE
mirror returning 503 requests

### ISSUE THREAD

**Issue by devinleighsmith** [bcgov/clamav-mirror#14] opened 2023-01-27 23:49 UTC
#### Describe the bug

As of this week, starting to see the following in my clamav pod logs:

Fri Jan 27 00:02:29 2023 -> !downloadFile: Unexpected response (503) from https://clamav-mirror.apps.silver.devops.gov.bc.ca/bytecode.cvd
Fri Jan 27 00:02:29 2023 -> !Can't download bytecode.cvd from https://clamav-mirror.apps.silver.devops.gov.bc.ca/bytecode.cvd
Fri Jan 27 00:02:29 2023 -> Giving up on https://clamav-mirror.apps.silver.devops.gov.bc.ca...

This isn't a major issue for me at the moment as the pod will failover to some default clam mirrors that are still working. However, I thought I would bring this to the attention of the maintainers in case they weren't aware the mirror was failing.

#### To Reproduce

check out the clamav image using this repo: https://github.com/bcgov/clamav
follow the instructions in that repo to deploy a new clamav instance.
check the pod logs, notice that all attempts to access the mirror are failing.

#### Expected behavior

the mirror should be returning the daily definition cvd.

#### Screenshots

![image](https://user-images.githubusercontent.com/41091511/215226655-eb3a6d06-e3ca-414d-ba1d-4ec40bba7440.png)

#### Desktop (please complete the following information)

NA

#### Smartphone (please complete the following information)

NA

#### Additional context

NA

**Comment by jujaga** [comment] 2023-01-30 18:09
Hi @devinleighsmith thank you for reporting this to us. We've applied a hotfix to bring the service back up; we weren't aware that it went down. o_o
Please check if your clamav updater is able to get the bytecode.cvd file again from our mirror and we can close the issue if everything is working as intended. Thanks!

**Comment by devinleighsmith** [comment] 2023-01-30 18:22
Thanks for doing that, I'll check on my end to see if it looks resolved.

**Comment by devinleighsmith** [comment] 2023-01-30 18:24
confirmed, issue appears resolved, getting 200's from the mirror now. Thanks again.

**Closed as completed** 2023-01-30 18:26 UTC
